COMEDY_FULL_TEXT = "./data/full-text.txt"
TOKEN_INDEX_MAP = "./bin/token_index.map"
INDEX_TOKEN_MAP = "./bin/index_token.map"
CHECKOUT_FOLDER = "./bin/checkpoint"

TOKEN_NUMBER = 38778
SENTENCES = 125986
MAX_LENGTH = 27
SKIP_STEP = 3

BATCH_SIZE = 100
EMBEDDING_SIZE = 100
SKIP_WINDOW = 3
OUTPUT_KEEP_PROB = 0.5